`Assiqnment6 - Numpy-II`

Q1. Consider the following sensor readings: 
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40]) 
A sensor has an average measurement error of +2°C. 
Perform the following without using a for loop: 
a. Add 2°C to every reading using vectorization. 
b. Convert all temperatures from Celsius to Fahrenheit.
c. Identify all readings greater than 32°C using Boolean indexing. 
d. Count how many readings exceed 32°C. 
e. Explain how vectorization and Boolean indexing can make data processing more efficient than explicitly iterating through every value. 

In [1]:
import numpy as np

temperature = np.array([25,28,31,35,38,27,33,40])
print("original array:", temperature)

cor_temp = temperature + 2
print("after addition of 2:", cor_temp)

original array: [25 28 31 35 38 27 33 40]
after addition of 2: [27 30 33 37 40 29 35 42]


In [2]:
mul = (9/5)*cor_temp
farh = mul + 32
print("temperature in fahrenheit",farh)

temperature in fahrenheit [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]


In [3]:
print(cor_temp > 32)

[False False  True  True  True False  True  True]


In [4]:
ct = np.sum(cor_temp > 32)
ct

np.int64(5)

Vectorization allows NumPy to perform an operation on an entire array at once instead of using a for loop for every element. It is generally faster because NumPy performs many operations using optimized low-level implementations.

Boolean indexing creates a Boolean condition such as:
cor_temp > 32
which can directly select only the elements satisfying the condition.

Therefore, vectorization and Boolean indexing make code:
Faster
Shorter
Easier to read
More efficient for large datasets
Less dependent on explicit Python loops


Q2. The following matrix represents the number of daily steps recorded by four users 
over three days: 
        steps = np.array([ 
        [5000, 6200, 7100], 
        [8000, 7500, 9000], 
        [4500, 5100, 4800], 
        [9000, 8500, 9500]]) 
Perform the following: 
a. Calculate the total steps recorded. 
b. Calculate the mean number of steps. 
c. Find the maximum and minimum values. 
d. Calculate the total steps for each day using axis=0. 
e. Calculate the total steps for each user using axis=1. 
f. Find the user/day position containing the maximum number of steps using argmax().

In [5]:
steps = np.array([[5000,6200,7100],[8000,7500,9000],[4500,5100,4800],[9000,8500,9500]])
total_steps = np.sum(steps)
total_steps

np.int64(84200)

In [6]:
mn = np.mean(steps)
mn

np.float64(7016.666666666667)

In [7]:
mx = np.max(steps)
mn = np.min(steps)
print(mx)
print(mn)

9500
4500


In [8]:
total_steps_col = np.sum(steps,axis= 0)
total_steps_row = np.sum(steps,axis= 1)
print(total_steps_col)
print(total_steps_row)

[26500 27300 30400]
[18300 24500 14400 27000]


In [9]:
max_position = np.argmax(steps)
max_position_2d = np.unravel_index(np.argmax(steps), steps.shape)

print("f. Flattened position of maximum:", max_position)
print("   User/day position of maximum:", max_position_2d)

f. Flattened position of maximum: 11
   User/day position of maximum: (np.int64(3), np.int64(2))


Q3. Write a Python program using NumPy to perform the following operations: 
a. Create the following NumPy array:
        original = np.array([1, 2, 3, 4, 5, 6]) 

b. Create a slice containing elements from index 1 to 4 and store it in a variable named subset. 
c. Modify the first element of subset to 999 and display both original and subset. 
d. Create another slice from original, but this time use .copy(). Modify its first element to 500 
and display original and the copied array. 
e. Create a NumPy array containing the numbers from 1 to 12 using np.arange() and reshape it 
into a 3 × 4 matrix. 
f. From the 3 × 4 matrix, extract the following using NumPy indexing and slicing: 
• First row  
• Last row  
• Second column  
• Elements from rows 1–2 and columns 2–3  
g. Create a flattened version of the 3 × 4 matrix using both flatten() and ravel(). 
h. Modify an element in the array returned by ravel() and observe whether the original array is 
affected. 
i. Modify an element in the array returned by flatten() and observe whether the original array is 
affected. 
j. Display the shape, ndim, size, and dtype of the original 3 × 4 matrix. 

In [10]:
original = np.array([1,2,3,4,5,6])
subset = original[1:4]
subset[0] = 999
print(original)
print(subset)

[  1 999   3   4   5   6]
[999   3   4]


In [11]:
sub = original[1:4].copy()
sub[0] = 500
print(original)
print(sub)

[  1 999   3   4   5   6]
[500   3   4]


In [12]:
arr = np.arange(1,13,1)
arr = arr.reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
first_row = arr[0]
last_row = arr[-1]
second_col = arr[:,1]
selected_elements = arr[0:2,1:3]


print("   First row:", first_row)
print("   Last row:", last_row)
print("   Second column:", second_col)
print("   Rows 1-2 and columns 2-3:")
print(selected_elements)


   First row: [1 2 3 4]
   Last row: [ 9 10 11 12]
   Second column: [ 2  6 10]
   Rows 1-2 and columns 2-3:
[[2 3]
 [6 7]]


In [14]:
flattened = arr.flatten()
raveled = arr.ravel()
print(flattened)
print(raveled)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
raveled[0] = 1000
print("   Matrix after modifying ravel():")
print(arr)
print("   Raveled array:", raveled)

   Matrix after modifying ravel():
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
   Raveled array: [1000    2    3    4    5    6    7    8    9   10   11   12]


In [16]:
flattened[1] = 2000

print("   Matrix after modifying flatten():")
print(arr)
print("   Flattened array:", flattened)

   Matrix after modifying flatten():
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
   Flattened array: [   1 2000    3    4    5    6    7    8    9   10   11   12]


In [17]:
print("   Shape:", arr.shape)
print("   Dimensions:", arr.ndim)
print("   Size:", arr.size)
print("   Data type:", arr.dtype)

   Shape: (3, 4)
   Dimensions: 2
   Size: 12
   Data type: int64


Q4. A simple cognitive-assistive system wants to predict a user's assistance score based 
on three factors: 
• Sleep hours  
• Activity level  
• Stress level  
Consider:
            X = np.array([ 
            [6, 70, 3], 
            [5, 50, 6], 
            [8, 80, 2], 
            [4, 30, 8] 
            ]) 

            y = np.array([40, 65, 30, 85]) 

Here, each row represents one user and each column represents a feature. 
Perform the following: 
a. Display the shape and dimensions of X. 
b. Calculate: X.T and explain what the transpose represents. 
c. Calculate the matrix product: X.T @ X 
d. Calculate the matrix inverse using: np.linalg.inv() where appropriate. 
e. Implement the Ordinary Least Squares equation: 𝛽 = (𝑋𝑋) 𝑋𝑦 using NumPy. 
f. Explain what the resulting coefficients represent in the context of the three user 
features. 
g. A new user has: new_user = np.array([5, 40, 7]) Use your calculated coefficients to obtain a predicted assistance score.

In [18]:
x = np.array([
    [6,70,3],
    [5,50,6],
    [8,80,2],
    [4,30,8]
])
y = np.array([40,65,30,85])

In [19]:
print(x.shape)
print(x.ndim)

(4, 3)
2


In [20]:
xtrans = x.T
print(xtrans)

[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]


In [21]:
xtx = x.T @ x
print(xtx)

[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


In [22]:
xtx_inverse = np.linalg.inv(xtx)
print(xtx_inverse)

[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]


In [23]:
bi = xtx_inverse @ xtrans @ y
print(bi)

[-0.15921454  0.14083853 10.06302242]


In [24]:
print("Coefficient interpretation:")
print("Sleep coefficient:", bi[0])
print("Activity coefficient:", bi[1])
print("Stress coefficient:", bi[2])

Coefficient interpretation:
Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587


In [25]:
new_user = np.array([5, 40, 7])

predicted_score = new_user @ bi

print("\ng. Predicted assistance score:", predicted_score)


g. Predicted assistance score: 75.27862544779117
